name: Deploy to AWS ECS
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and Push Docker Image
        run: |
          docker build -t llm-api .
          docker tag llm-api:latest <your-ecr-uri>:latest
          docker push <9760-4829-8888>:latest          